### ISSUE TITLE
Extension does not seem to work with Moodle 4.2

### ISSUE THREAD

**Issue by todbaadle** [harsilspatel/moodle-downloader#36]
I would first like to thank the wonderful creators of this extension. Your work is highly appreciated.
May I know if there is an upcoming update to the extension so that it supports Moodle 4.2 version?

I did run a couple of tests, and it doesnt seem to load the resources for download for Moodle 4.2.

Thank you in advance.

**Comment by harsilspatel** [comment]
Thanks for your kind words!

Unfortunately, I can no longer offer support for the extension since I developed it as a student and have graduated since.

You might find other Moodle downloader extensions that work [under the "Related"](https://chrome.google.com/webstore/detail/moodle-downloader/ohhocacnnfaiphiahofcnfakdcfldbnh) tab in the Chrome Web Store.
